### ISSUE TITLE
Will we plan to support google protocol buffer v3?

### ISSUE THREAD

**Issue by xiemalin** [square/protoparser#103]
alpha version is out here
https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-2

**Comment by JakeWharton** [comment]
Version 4 already does.

**Comment by swankjesse** [comment]
Also, we're in the process of moving this code:
https://publicobject.com/2015/07/13/protoparser-is-going-away/

**Comment by xiemalin** [comment]
But I found that map element is not supported yet of version 4.0.3

java.lang.IllegalStateException: Syntax error in jprotobuf_autogenerate at 14:6: unexpected label: map
	at com.squareup.protoparser.ProtoParser.unexpected(ProtoParser.java:947)
	at com.squareup.protoparser.ProtoParser.readDeclaration(ProtoParser.java:197)
	at com.squareup.protoparser.ProtoParser.readMessage(ProtoParser.java:219)
	at com.squareup.protoparser.ProtoParser.readDeclaration(ProtoParser.java:153)
	at com.squareup.protoparser.ProtoParser.readProtoFile(ProtoParser.java:92)
	at com.squareup.protoparser.ProtoParser.parse(ProtoParser.java:56)
	at com.squareup.protoparser.ProtoParser.parseUtf8(ProtoParser.java:45)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.create(ProtobufIDLProxy.java:203)
	at com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.create(ProtobufIDLProxy.java:199)
	at com.baidu.bjf.remoting.protobuf.idlproxy.map.MapTypeIDLProxyTest.testSimpleMap(MapTypeIDLProxyTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by xiemalin** [comment]
syntax = "proto3";
// See README.txt for information and build instructions.

package com.baidu.bjf.remoting.protobuf.v3;



option java_package = "com.baidu.bjf.remoting.protobuf.idlproxy.map";
option java_outer_classname = "AddressBookProtos";

message Person {
  required string name = 1;
 
  map<string, string> stringMap = 2;

	map<int32, int32>  intMap = 3;
	
	map<int64, int64> longMap = 4;
	
	map<bool, bool> booleanMap = 5;

}

**Comment by xiemalin** [comment]
I found the problem,  using google protocol buffer compile tool to compile proto file has follow constraint, but protoparser must add field labels (required/optional/repeated) on map field.

protoc3 --java_out=. simple-map.proto
simple-map.proto:14:15: Field labels (required/optional/repeated) are not allowed on map fields.

**Comment by swankjesse** [comment]
Agreed. Follow along here:
https://github.com/square/wire/issues/279
